### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by kotborealis**

### CODE REVIEW

**Comment by VladimirMakaev** [comment]
Thanks for the fix!  Please sign the CLA in order to have this to get through (as per https://github.com/facebookexperimental/hermit/blob/main/CONTRIBUTING.md)

**Comment by kotborealis** [comment]
Signed the CA just now 👍

**Comment by VladimirMakaev** [comment]
We currently have some desync issues with internal repo & github. I'll merge this once we get back up in sync. Thanks for your contribution!

**Comment by caizixian** [comment]
@kotborealis Could you also integrate this commit https://github.com/caizixian/hermit/commit/29a4abd9f5f87c821aabf813894dbe69c3e54ca3
The hyperlink is broken after removing the backtick

**Comment by kotborealis** [comment]
@caizixian cherry-picked & merged your commit, thanks!

**Pull request closed without merging**
